### ISSUE TITLE
Restructure code to allow separation of data and control planes across different machines

### ISSUE THREAD

**Issue by anyoung** [project8/phasmid#1]
The current implementation of the interface library assumes that the same machine that controls the ROACH2 also captures the data that the ROACH2 sends. The library needs to be restructured such that the data plane can be configured independently.

The proposed solution is to implement class methods in `ArtooDaq` that allow configuring the data network ports independently. Configuration presently needs:
- IP-port pair for the destination (zeppelin, or equivalent),
- an IP-port pair for the source (ROACH2),
- a MAC address for the interface on the ROACH2, and
- an ARP table entry for the destination.

So then for each digital channel a component that interfaces with `ArtooDaq` could just do something like:

`r2.configure_dplane(channel='a', src_soc=('10.0.0.3',4000), src_mac='ab:cd:ef:01:23:45', dest_soc=('10.0.0.1',4001), dest_mac='12:34:45:67:89:ab')`

In the current implementation the configuration is easily automated: using `netifaces` the control machine can determine all of the above, given the network interface that it should use to receive data. 

Separating the control / data it should be possible in principle to have a similar automated process where the data target is similarly identified by higher-level hostname / interface. On the other hand it may be simpler (not only for development, but perhaps also from a management perspective) to do the configuration using the needed lower-level parameters. In terms of integration with the wider system, is there a preference for one or the other?

/cc @cclaessens @nsoblath @laroque @wcpettus

**Comment by laroque** [comment]
Um... most likely these parameters will just end up in a yaml config file, so it is fine to just have the method signature as shown in the issue post above.

**Comment by anyoung** [comment]
Okay, r2daq.py should now be able to start the system with more general IP settings. There are also some changes made toward porting into dragonfly, see the `port-to-dragonfly` branch.

Is there a better way to add r2daq.py to dragonfly than just manually git-add'ing the file?

**Comment by laroque** [comment]
One can extract a file with its history from one repo into another. My best procedure for that looks like the sequence below.

However, I believe that @cclaessens has already moved an older version of r2daq.py into dragonfly. Therefore it is probably best to either diff the two and manually merge the conflicts (or if she hasn't made changes just use your new file). It may also be possible to generate a patch based on your changes and apply it to her version in dragonfly so that both changes can be maintained.

```
# create the filter branch
git filter-branch --subdirectory-filter <path/to/directory/to/extract> HEAD
git reset --hard
git gc --aggressive
# put filtered content into desired path for destination repo
mkdir -p <desired/directory/within/destination/repo>
git mv ./* <desired/directory/within/destination/repo>
git add <desired/directory/within/destination/repo>
git commit -m "<something useful>"
# push content to new repo and integrate
git remote add <name_of_destination_repo_remote> <path/to/clone/of/remote>
git push <name_of_destination_repo_remote> <name_of_new_remote_branch>
cd <path/to/clone/of/remote>
git checkout [-b] <name_of_local_branch_to_merge_directory_into>
git merge --no-ff <name_of_new_remote_branch>
```

**Comment by anyoung** [comment]
Thanks, this will come in very handy one day.

I just pushed the updates in r2daq.py to dragonfly and future development will continue there.

**Comment by cclaessens** [comment]
The r2daq.py in my dragonfly version was just a copy of an old version. I installed the dependencies on my laptop. Maybe they could be included in the dragonfly requirements so they can be installed along with the dragonfly dependencies?
